export const DETAIL_PRODUCT = "DETAIL_PRODUCT";
export const STORE_DETAIL = "STORE_DETAIL";
export const VIEW_STORE_DETAIL = "VIEW_STORE_DETAIL";
export const RESET_STORE_DETAIL = "RESET_STORE_DETAIL";
